### ISSUE TITLE
Emitter and infinite emitter not working !

### ISSUE THREAD

**Issue by Skillotic0703** [jakimfett/ParticlePhysics#19]
I can't put an element in those machines without shift right-clicking. When i put an element in one of those machines, it says type:blank at the right and it doesn't emit particles ! 
I can reproduce the bug.
It seems to happen with all elements. I tested with carbon, hydrogen, kaolinite and oxygen.
I'm using the latest forge (10.13.3.1424)
I'm using the latest versions of CoFHCore and the latest minechem and particle physics versions.

**Comment by jakimfett** [comment]
Could I get you to read over the [Bug Reporting Guidelines](https://github.com/jakimfett/ParticlePhysics/wiki/Bug-Reporting-Guidelines) and update your ticket, please?

**Comment by Skillotic0703** [comment]
The config file is empty! Even when i delete the config file and reload minecraft!

**Comment by way2muchnoise** [comment]
@Skillotic0703 it isn't working with minechem elements any more try
* coal
* blaze powder
* clay ball
* gunpowder
* seeds
* paper
* sand
* leaves
* glass

**Comment by Skillotic0703** [comment]
Oups !!! I'm sorry !!!

**Comment by Skillotic0703** [comment]
OUUUPSSS !

**Comment by jakimfett** [comment]
I added the particles info to the CurseForge download page.
