### ISSUE TITLE
Feature Suggestion: Particle Accelerator 

### ISSUE THREAD

**Issue by Badcholo** [jakimfett/ParticlePhysics#20]
Creating a Particle Accelerator using Acceleration blocks that loop and gain speed as they move. lose speed as they turn. When the particle accelerates reaches it's max speed you are able to produce Antimatter. Antimatter can be used to craft an Antimatter Bomb, such as ICBM had in 1.5.2. 
1.7.10 has been dying for a good explosives mod.
Nuclear bomb crafted with 8 1g antimatter around it to create a antimatter bomb.
9 125mg of antimatter crafted to create 1g of antimatter. 
Other uses for antimatter can be used as a fuel to generate power in a Atomic Generator. 
Generating power from creating a small black hole. idk, now i'm just making stuff up.
nice mod, but hard to learn and setup to just produce power. solar panels, coal generators, biofuel generators also create power without such a complicated setup, RF windmills, water generators, ect.
I really like this mod if there was a process for producing some sort of new mineral that was only obtainable and could be used for other purposes.

**Comment by jakimfett** [comment]
So...you're basically asking me to blatantly rip off the Atomic Science mod? And possibly bits from Mekanism?

**Comment by Badcholo** [comment]
There are so many mods that are similar. Just cause one mod adds in a few items instead of settling for the whole mod doesn't mean you ripped them off. plus it's not like you would be stealing their code. Everything that i mentioned has nothing to do with mekanism. The other ideas are similar and i only mentioned the other mods for reference, not for you to go and steal their mods. Also just cause a mod uses antimatter doesn't mean all other mods can't use it. Just cause antimatter was used in an explosive doesn't mean a different mod can't use it to generate power in different ways. Sorry you took my comment the wrong way. I wrote it quickly.
